name: Update Age in README

on:
  schedule:
    - cron: '0 0 8 7 *'  # Runs every July 8 at midnight UTC
  workflow_dispatch:  # Allows manual trigger

permissions:
  contents: write  # Grants permission to push changes

jobs:
  update-age:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false  # Disable default authentication

      - name: Configure Git User
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Update Age in README
        run: |
          BIRTH_YEAR=2009
          CURRENT_YEAR=$(date +%Y)
          CURRENT_MONTH=$(date +%-m)
          CURRENT_DAY=$(date +%-d)

          AGE=$((CURRENT_YEAR - BIRTH_YEAR))

          # Adjust if birthday hasn't happened yet this year
          if [ "$CURRENT_MONTH" -lt 7 ] || ([ "$CURRENT_MONTH" -eq 7 ] && [ "$CURRENT_DAY" -lt 8 ]); then
            AGE=$((AGE - 1))
          fi

          echo "Calculated Age: $AGE"

          # Debugging: Show README before change
          echo "Before update:"
          cat README.md

          # Update README.md
          sed -i "s/\*\*{{AGE}}\*\*/\*\*$AGE\*\*/g" README.md

          # Debugging: Show README after change
          echo "After update:"
          cat README.md

      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add README.md
          git commit -m "Update age in README for $CURRENT_YEAR" --allow-empty
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git HEAD:main
